### ISSUE TITLE
tensorflow version update

### ISSUE THREAD

**Issue by mitezo** [mgoubran/VentMapp3r#3]
VentMapp3r GPU requires tensorflow-gpu==1.4.0 which depends on CUDA 9.
I would like to use VenrMapp3r GPU with CUDA 10.
Do you have a plan to update the dependency of VentMapp3r GPU to enable it to run with tensorflow-gpu >= 2.0.0?

**Comment by srivathsapv** [comment]
You can change https://github.com/mgoubran/VentMapp3r/blob/master/setup.py#L39 to `keras==2.3.1` or whichever version that suits your CUDA drivers. Similarly you can change line 44 to `tensorflow-gpu >= 2.0.0` and re-run the `pip install -e .` command. It worked for me.

**Comment by mitezo** [comment]
It worked in my environment. Thank you for your kind answer!
